# Generated by Django 2.2.6 on 2019-10-31 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=100)),
                ('lat', models.CharField(max_length=100)),
                ('lng', models.CharField(max_length=100)),
                ('phone_order', models.BooleanField(default=False)),
                ('free_delivery_threshold', models.IntegerField()),
                ('delivery_fee_explanation', models.CharField(max_length=200)),
                ('threshold', models.IntegerField()),
                ('logo_url', models.URLField(max_length=400)),
                ('estimated_delivery_time', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('review_count', models.IntegerField()),
                ('open_time_description', models.CharField(max_length=100, null=True)),
                ('additional_discount', models.IntegerField()),
                ('review_image_count', models.IntegerField()),
                ('is_available_pickup', models.BooleanField()),
                ('delivery_fee', models.IntegerField()),
                ('review_avg', models.IntegerField()),
                ('one_dish', models.BooleanField()),
            ],
            options={
                'db_table': 'restaurants',
            },
        ),
        migrations.CreateModel(
            name='Restaurants_Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.Restaurants')),
            ],
            options={
                'db_table': 'restaurants_tags',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('restaurant', models.ManyToManyField(through='restaurant.Restaurants_Tags', to='restaurant.Restaurants')),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.AddField(
            model_name='restaurants_tags',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.Tags'),
        ),
        migrations.CreateModel(
            name='Restaurants_Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.Categories')),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.Restaurants')),
            ],
            options={
                'db_table': 'restaurants_categories',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurants')),
            ],
            options={
                'db_table': 'payment_methods',
            },
        ),
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('image', models.URLField(max_length=400)),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.Restaurants')),
            ],
            options={
                'db_table': 'menus',
            },
        ),
        migrations.AddField(
            model_name='categories',
            name='restaurant',
            field=models.ManyToManyField(through='restaurant.Restaurants_Categories', to='restaurant.Restaurants'),
        ),
    ]
