# Generated by Django 2.2.6 on 2019-11-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20191102_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menus',
            name='image',
            field=models.CharField(max_length=4000, null=True),
        ),
    ]
