# Generated by Django 2.2.6 on 2019-10-31 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20191101_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menus',
            name='image',
            field=models.CharField(max_length=4000, null=True),
        ),
    ]
