# Generated by Django 2.2.6 on 2019-10-31 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20191101_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='additional_discount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='delivery_fee_explanation',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='estimated_delivery_time',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='free_delivery_threshold',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='is_available_pickup',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='logo_url',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='one_dish',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='phone_order',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='review_avg',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='review_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='review_image_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='threshold',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
