# Generated by Django 2.2.6 on 2019-11-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20191101_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menus',
            name='image',
            field=models.URLField(max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='logo_url',
            field=models.URLField(max_length=4000, null=True),
        ),
    ]
