# Generated by Django 2.2.6 on 2019-11-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_auto_20191101_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='company_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='company_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='ingredients_origin',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='review_avg',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
    ]
