# Generated by Django 2.2.6 on 2019-11-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_auto_20191102_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='ingredients_origin',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
