# Generated by Django 2.2.6 on 2019-11-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_auto_20191102_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='ingredients_origin',
            field=models.TextField(null=True),
        ),
    ]
