# Generated by Django 2.2.6 on 2019-10-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=500)),
                ('nickname', models.CharField(max_length=400, null=True)),
            ],
            options={
                'db_table': 'users_list',
            },
        ),
    ]
