# Generated by Django 2.2.6 on 2019-10-29 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPlatforms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='joined_platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.SocialPlatforms'),
        ),
    ]
