# Generated by Django 2.2.6 on 2019-10-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191029_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='joined_platform',
        ),
        migrations.AddField(
            model_name='socialplatforms',
            name='user',
            field=models.ManyToManyField(to='user.Users'),
        ),
        migrations.AddField(
            model_name='users',
            name='email_accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='is_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='phone_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
