# Generated by Django 2.2.6 on 2019-10-29 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191029_1506'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='socialplatforms',
            table='SocialPlatforms',
        ),
    ]
