# Generated by Django 2.2.6 on 2019-10-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20191029_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_user',
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='nickname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.CharField(blank=True, default='nothing', max_length=100),
            preserve_default=False,
        ),
    ]
