# Generated by Django 2.2.6 on 2019-10-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20191029_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
