# Generated by Django 2.2.6 on 2019-10-30 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20191029_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'social_platforms',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=70, unique=True)),
                ('password', models.CharField(max_length=400)),
                ('email_accept', models.BooleanField(default=False)),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('social_platform', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.SocialPlatform')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.DeleteModel(
            name='SocialPlatforms',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
